import { SearchIcon } from "@heroicons/react/solid";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gradient-to-tr from-primary via-primary to-secondary h-screen">
        <h1 className="text-white ml-2 text-xl">Logo</h1>
        <h1 className="text-lg text-white ml-2 mt-5">Selamat Datang Maurice Yang</h1>
        <h1 className="text-white ml-2 text-3xl mb-5">Mencari makan di UI tak pernah semudah ini</h1>
        <div className="relative">
          <input placeholder="Cari Kantin" type="search" className="input-field placeholder:text-white mb-5 border-white border-4 bg-transparent text-white focus:bg-white focus:text-black" />
          {/* <SearchIcon className="w-5 h-5 absolute" /> */}
        </div>
        <section className="h-full w-full bg-white rounded-t-3xl p-3">
          <h2 className="text-xl"></h2>
          <Link href="/explore">
            <a className="btn btn-primary w-full">Lihat Semua</a>
          </Link>
        </section>
      </main>
    </>
  );
};


export default Home;
